#pragma once
// This gets included from C, C++, and assembly, so we can basically only
// #define

#define REDZONE_SIZE 128
#define STACK_SIZE 0x8000000

#define SHADOW_STACK_FRAME_SIZE 86

// Offsets of fields within struct abisan_shadow_stack_frame
#define FRAME_RETADDR 0x00
#define FRAME_RBX 0x08
#define FRAME_RBP 0x10
#define FRAME_RSP 0x18
#define FRAME_R12 0x20
#define FRAME_R13 0x28
#define FRAME_R14 0x30
#define FRAME_R15 0x38
#define FRAME_INSTRUMENTATION_RETADDR 0x40
#define FRAME_RFLAGS 0x48
#define FRAME_X87CW 0x50
#define FRAME_FS 0x52
#define FRAME_MXCSR 0x54

// Offsets of fields within struct abisan_taint_state
#define TAINT_STATE_RAX 0
#define TAINT_STATE_EAX TAINT_STATE_RAX
#define TAINT_STATE_AX TAINT_STATE_RAX
#define TAINT_STATE_AH TAINT_STATE_RAX
#define TAINT_STATE_AL TAINT_STATE_RAX

#define TAINT_STATE_RBX 1
#define TAINT_STATE_EBX TAINT_STATE_RBX
#define TAINT_STATE_BX TAINT_STATE_RBX
#define TAINT_STATE_BH TAINT_STATE_RBX
#define TAINT_STATE_BL TAINT_STATE_RBX

#define TAINT_STATE_RCX 2
#define TAINT_STATE_ECX TAINT_STATE_RCX
#define TAINT_STATE_CX TAINT_STATE_RCX
#define TAINT_STATE_CH TAINT_STATE_RCX
#define TAINT_STATE_CL TAINT_STATE_RCX

#define TAINT_STATE_RDX 3
#define TAINT_STATE_EDX TAINT_STATE_RDX
#define TAINT_STATE_DX TAINT_STATE_RDX
#define TAINT_STATE_DH TAINT_STATE_RDX
#define TAINT_STATE_DL TAINT_STATE_RDX

#define TAINT_STATE_RDI 4
#define TAINT_STATE_EDI TAINT_STATE_RDI
#define TAINT_STATE_DI TAINT_STATE_EDI
#define TAINT_STATE_DIL TAINT_STATE_DI

#define TAINT_STATE_RSI 5
#define TAINT_STATE_ESI TAINT_STATE_RSI
#define TAINT_STATE_SI TAINT_STATE_ESI
#define TAINT_STATE_SIL TAINT_STATE_SI

#define TAINT_STATE_R8 6
#define TAINT_STATE_R8D TAINT_STATE_R8
#define TAINT_STATE_R8W TAINT_STATE_R8
#define TAINT_STATE_R8B TAINT_STATE_R8

#define TAINT_STATE_R9 7
#define TAINT_STATE_R9D TAINT_STATE_R9
#define TAINT_STATE_R9W TAINT_STATE_R9
#define TAINT_STATE_R9B TAINT_STATE_R9

#define TAINT_STATE_R10 8
#define TAINT_STATE_R10D TAINT_STATE_R10
#define TAINT_STATE_R10W TAINT_STATE_R10
#define TAINT_STATE_R10B TAINT_STATE_R10

#define TAINT_STATE_R11 9
#define TAINT_STATE_R11D TAINT_STATE_R11
#define TAINT_STATE_R11W TAINT_STATE_R11
#define TAINT_STATE_R11B TAINT_STATE_R11

#define TAINT_STATE_R12 10
#define TAINT_STATE_R12D TAINT_STATE_R12
#define TAINT_STATE_R12W TAINT_STATE_R12
#define TAINT_STATE_R12B TAINT_STATE_R12

#define TAINT_STATE_R13 11
#define TAINT_STATE_R13D TAINT_STATE_R13
#define TAINT_STATE_R13W TAINT_STATE_R13
#define TAINT_STATE_R13B TAINT_STATE_R13

#define TAINT_STATE_R14 12
#define TAINT_STATE_R14D TAINT_STATE_R14
#define TAINT_STATE_R14W TAINT_STATE_R14
#define TAINT_STATE_R14B TAINT_STATE_R14

#define TAINT_STATE_R15 13
#define TAINT_STATE_R15D TAINT_STATE_R15
#define TAINT_STATE_R15W TAINT_STATE_R15
#define TAINT_STATE_R15B TAINT_STATE_R15

#define TAINT_STATE_RBP 14
#define TAINT_STATE_EBP TAINT_STATE_RBP
#define TAINT_STATE_BP TAINT_STATE_RBP
#define TAINT_STATE_BPL TAINT_STATE_RBP

#define TAINT_STATE_RFLAGS 15
#define TAINT_STATE_EFLAGS TAINT_STATE_RFLAGS
#define TAINT_STATE_FLAGS TAINT_STATE_RFLAGS
